### ISSUE TITLE
Sociální a další ikonky bez Font Awesome

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/frontierline-mozillacz#3]
S ohledem na design šablony bychom možná mohli používat místo Font awesome jen texty, případně zpět SVG ikony jako součást šablony. Pokud jich nebude tolik.

**Comment by jrychly** [comment]
Já bych zachoval Font awesome, ale je zase pravda, že ho využíváme jen pro malou část. V tom případě bych se přikláněl k SVGčkám.

**Comment by vasimi** [comment]
Dřív existovala zdarma varianta fortawesome.com, kde sis mohl navolit pár ikonek a oni ti je posílali z CDNky. To už očividně nefunguje. Ale FA5 (který jsi nějak ignoroval @MikkCZ) už distribuuje samostatné SVGčka, by-default má i „svg-in-js“, ne webfonts variantu. Kdyby se vyčistily ty JS od zbytečných ikonek, tak nám bude fungovat i `<i class="fa fab-facebook-f"></i>`.

**Comment by vasimi** [comment]
Aha, tak to vypadá, že Free plan ještě pořád nabízí, jen ho nemají v ceníku. Vydal bych se teda touhle cestou, vyvážení trafficu a vopruzu při kódování je tam asi nejlepší.
// Nenabízí.

**Comment by vasimi** [comment]
@MikkCZ Mám nějak pročistit ten FA5, abychom tam měli jen to nejnutnější, a poslat PR? Nebo se vydáme jinou cestou?

**Comment by MikkCZ** [comment]
Nechme to zatím takto. Ta pětka se mi nelíbí, protože není ve veřejných CDN a musíš si ji registrovat (nebo alespoň to bylo posledně když jsem se díval potřeba). A přímo do šablony to začleňovat a udržovat nechci. Spíš se podívám na obsah a zjistím, jestli vůbec Font Awesome potřebujeme. Až upravím stránky ke stažení tak si myslím, že ani ne.

**Comment by vasimi** [comment]
Pětka je ve veřejných CDN a nemusíš ji registrovat. To platí jenom o Pročku.

**Comment by MikkCZ** [comment]
Pošli mi tedy prosím link.

--
Michal Stanke

**Comment by vasimi** [comment]
https://fontawesome.com/get-started

**Comment by MikkCZ** [comment]
Tak to je novinka. Když jsem se díval někdy před tím měsícem, běžet web ještě na doméně fontawesome.io a muselo se pro pětku registrovat. Už to tedy testuju.

**Comment by vasimi** [comment]
Jo, ale to byla ještě čtyřková CDNka. Oni si stejně jen mailem poslali link na ty soubory a nic víc jsi dělat nemusel.

**Comment by MikkCZ** [comment]
Font Awesome 5 je tam. Připravil jsem pro to i CSP na mozilla.cz, aby se to po nasazení nerozbilo. Každopádně FA se teď používá na:
- ikonku podpory ve widgetu
- ikonky sociálních sítí ve widgetech
- ikonku Firefoxu ve widgetu s příští verzí
- ikonky platforem (a lokalizačního balíčku) na stránkách ke stažení
- ikonky na stránce Zapojte se

V tuto chvíli bych tedy u FA zůstal a jenom jeho použití dál nerozšiřoval, určitě ne do zpráviček.
