### ISSUE TITLE
Umístění loga

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/frontierline-mozillacz#6]
V https://github.com/craigcook/frontierline-theme/pull/13 jsme vyškrtli logo v záhlaví. Musíme tedy najít jiné řešení. Buď dát tuto změnu do child vzhledu, nebo dát logo jako součást obrázku v pozadí záhlaví (podle toho bude #2).

**Comment by MikkCZ** [comment]
Aktuální logo v záhlaví na frontier.mozilla.cz - https://screenshots.firefox.com/3I5mcdKILQHPEK1v/frontier.mozilla.cz

[frontier-header-mozillacz-03.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58404bf15046691300820bfd/125516c66e82c728ace21e0d46ee86952d968aac9da4b746a559f586644b28692008af2a739fae78ec0037431f1d11f6140b1b56f6eb8c23a2b639738e5802bf833e0925923411adbcd31abc07b832975dc7e7e2de139db17770a599855d3c1c0f198cfd5d3da09a4bcf5cf54fe65f18.zip)

**Comment by MikkCZ** [comment]
@MozillaCZ/web jak to vypadá?

**Comment by jrychly** [comment]
Podle mě je to v pohodě tak, jak to je :) na mobilu to není vůbec, což je v pořádku. A nakloněné to vypadá dobře.

**Comment by MikkCZ** [comment]
Co na to říkáte @MekliCZ @zelitomas ?

**Comment by vasimi** [comment]
Je to zvláštní, ale je to celkem hezký. Asi hezčí, než kdyby bylo v tom navbaru.
